language: ruby
rvm:
- 2.6.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- bundle exec jekyll build
cache: bundler
deploy:
  provider: s3
  access_key_id: "${S3_ACCESS_KEY_ID}"
  secret_access_key: "${S3_SECRET}"
  skip_cleanup: true
  bucket: sc-lib-ds-static
  local_dir: _site
  upload_dir: human-monsters
  detect_encoding: true
  default_text_charset: utf-8
branches:
  only:
  - master
notifications:
  slack:
    secure: qgjFa1IRMOwbaaD4FZNBYqPyInc2774LJO09N4Hah7V6E9RYAhF2sh6xpnIqhIaeD3po/QrZVAUWNmjCXhu1pLlpYPipPoqyQL3bWauV06GX0GaomBMTTiBeDni/e5b+aU7reolqpALngyZ45VX0GZ1MGUMjzoOOIm0J0aynsCQJkhHV4tZ3oGAAF1I8o7v9D7j+KBDw6bALM4oOvMfQpRhOayFkxbHt5gmThusxYkApjR6mFQ3CCAn996dHVHZU3cwguCabcXNOxBT94jjAxrdEK/ewdZqKdxdzHdhnOjfdLycUWXqA0seHsYAz375+EYl7e2LEtTk1KJ67rvpuq1uG91P10TgI928YvQRseEUbpwb/6/KMjZ3QjsBlwbqPdQdShnqQ+wkD44t05i25zlMOxcENja2h473Y6NW/OWIJ+SRc2R3IjfYzRTp+8/QGzTwBYMxp5lX1U9cGVJgihe2pS3BRUJ0SKJB+295DJDGRN71N2EsxsGbMBgMXPnkW4Mba3GO1Y+6ywl2p9s/jBszIKNUkYRYBc5++WVJiWx2j92rGCYqKqu0HXHXrTv9L2oyJYRNHoIOR75cU/xfQhpT5H7y3xfpeLIwnts7VPRAOmaDDwpoJHEi/z15qegH+CTQCQ2qWrkzxciqAG2ACXIbGj9fv9KpWpIWiXzpsBL0=
    on_success: always
    on_failure: always
