language: ruby
rvm:
- 2.6.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- bundle exec jekyll build
cache: bundler
deploy:
  provider: s3
  access_key_id: "${S3_ACCESS_KEY_ID}"
  secret_access_key: "${S3_SECRET}"
  cleanup: false
  bucket: sc-lib-ds-static
  local_dir: _site
  upload_dir: human-monsters
  detect_encoding: true
  default_text_charset: utf-8
branches:
  only:
  - master
notifications:
  slack:
    secure: lEuVKgQwWxsHB50P7bHTSTFQ81y4Omzf7heA5brG9CyI2AobAOCUJw4LS9Je5lrZ+hEb6bM7xo+YCiKJHwapvhkgTftxikcqVEcrcpqrcQfhkq4DnGCO56xdr7m5DyJgW102UGqIdAqr9voIhNWOH1LYSxxSAuk6G9htOC1wvmTc+0Hi86JP0Vw8NyVGWZ4EQiTbww8g7+Xv4JDGRQodPLZ5dXRLyIVt37XHc0/mIlPU9cYzMsrqPVdah+bEuYbzabLHBcAUhitSkZiPTg7puoKhGBc0TXXIq1NY2SLbTY5sr3SGjunAA4aJHqCjAywHnkPPkRfTdNrrIRK+iZBAr36mke56EQdzxl/hBJNmvWU83zsSarG+b7PgB/aJr13uFuEvhCb2Uk5fzY1OZjUtqmojwoGKgkIzJ+Rlqfbib0GXDCTfrtSCxwwtgLIXRWFVYCPSIAa3tR6NgGEyBD8UbvIhRsKAdSCvsKfbrND+lXrYULiQTPR4bgpJ+cHsVTmDrCtne8CIbE1j0kvkTLYwoPSt36hEHtUN0y/HBSKt5iDdQnaoKXWSy7JQ9IRfcK2zgTocrXvjchOxgB3YmA5FsAcJYfUvP87TD9db5aTf787D7+wlHNgxzWC86e6zPaE3xjazj1C2H6LlL3I5RWb9MUjDDTAWICTMPWJq4KAHZvc=
  email:
  - digitalscholarship@swarthmore.edu
